import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const _dirname = dirname(fileURLToPath(import.meta.url));

// 1. Inline github-markdown-css
const cssPath = join(_dirname, "..", "node_modules", "github-markdown-css", "github-markdown.css");
const css = readFileSync(cssPath, "utf-8");

// 2. Inline mermaid runtime (browser-side rendering, no Chrome needed at build time)
const mermaidPath = join(_dirname, "..", "node_modules", "mermaid", "dist", "mermaid.min.js");
const mermaidJs = readFileSync(mermaidPath, "utf-8");

const output = `// Auto-generated by scripts/prepare-sea.mjs — do not edit.
export const githubMarkdownCss = ${JSON.stringify(css)};

export const mermaidRuntimeJs = ${JSON.stringify(mermaidJs)};
`;

writeFileSync(join(_dirname, "..", "src", "assets.ts"), output, "utf-8");
console.log("✓ src/assets.ts generated (github-markdown-css + mermaid runtime)");
