import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const _dirname = dirname(fileURLToPath(import.meta.url));

// 1. Inline github-markdown-css
const cssPath = join(_dirname, "..", "node_modules", "github-markdown-css", "github-markdown.css");
const rawCss = readFileSync(cssPath, "utf-8");

// Extract the CSS custom-properties block for a given prefers-color-scheme scheme,
// then mirror it onto :root so the whole <body> (not just .markdown-body) can use it,
// and emit explicit [data-theme] overrides that win over the @media rules.
function extractVars(scheme) {
  const needle = `@media (prefers-color-scheme: ${scheme})`;
  const idx = rawCss.indexOf(needle);
  if (idx === -1) return "";
  const ruleOpen = rawCss.indexOf("{", rawCss.indexOf("{", idx) + 1);
  const declStart = ruleOpen + 1;
  let depth = 1, i = declStart;
  while (i < rawCss.length && depth > 0) {
    if (rawCss[i] === "{") depth++;
    else if (rawCss[i] === "}") depth--;
    i++;
  }
  return rawCss.slice(declStart, i - 1).trim();
}
const darkVars = extractVars("dark");
const lightVars = extractVars("light");
const themeOverrideCss = `
/* ponytail: mirror markdown CSS vars onto :root + .markdown-body with manual [data-theme] overrides.
   .markdown-body must be targeted too, otherwise its own @media-scoped vars (specificity 0,1,0)
   cut off :root inheritance. We beat them with :root[data-theme] .markdown-body (0,2,0). */
:root { ${lightVars} }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) { ${darkVars} }
}
:root[data-theme="dark"],
:root[data-theme="dark"] .markdown-body { ${darkVars} }
:root[data-theme="light"],
:root[data-theme="light"] .markdown-body { ${lightVars} }
`;
const css = rawCss + "\n" + themeOverrideCss;

// 2. Inline mermaid runtime (browser-side rendering, no Chrome needed at build time)
const mermaidPath = join(_dirname, "..", "node_modules", "mermaid", "dist", "mermaid.min.js");
const mermaidJs = readFileSync(mermaidPath, "utf-8");

const output = `// Auto-generated by scripts/prepare-sea.mjs — do not edit.
export const githubMarkdownCss = ${JSON.stringify(rawCss + themeOverrideCss)};

export const mermaidRuntimeJs = ${JSON.stringify(mermaidJs)};
`;

writeFileSync(join(_dirname, "..", "src", "assets.ts"), output, "utf-8");
console.log("✓ src/assets.ts generated (github-markdown-css + mermaid runtime)");
